services:
  - type: web
    name: aurovia-backend
    env: python
    plan: free
    rootDir: backend
    region: ohio # Change this to your preferred region (e.g. frankfurt, oregon, singapore)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0 # Enforces modern python
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT_URL
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
